<<<<<<< HEAD
[cookery]
	#Whether the Satiated Shield effect should absorb excess damage beyond its capacity.
	SatiatedShieldAbsorbExcessDamage = false
=======
[cookery]
	#Whether the Satiated Shield effect should absorb excess damage beyond its capacity.
	SatiatedShieldAbsorbExcessDamage = false
>>>>>>> 3612d525cf3693c9bb2f76017c5de69ef44185eb
